import Common.Const
CONST = Common.Const


def print_info():
    print("-------------------------------------------")
    print("客户")
    print("客户名称：" + CONST.CUSTOM_NAME)
    print("客户code：" + CONST.CUSTOM_CODE)
    print("ServicePort：" + CONST.CUSTOM_SERVICE_PORT)
    print("-------------------------------------------")
    print("项目：" + CONST.PROJECT_NAME_EN)
    print("-------------------------------------------")
    print("RabbitMQ")
    print("地址：" + CONST.RABBITMQ_ADDRESS)
    print("Virtual Hosts：" + CONST.RABBITMQ_VIRTUAL_HOST)
    print("-------------------------------------------")
    print("Exceptionless")
    print("客户：" + CONST.EXCEPTIONLESS_CUSTOM_NAME)
    print("地址：" + CONST.EXCEPTIONLESS_ADDRESS)
    print("Key：" + CONST.EXCEPTIONLESS_KEY)
    print("-------------------------------------------")
    print("服务器IP地址：" + CONST.SERVER_IP)
    print("-------------------------------------------")
    print("服务号Appid：" + CONST.SERVICE_APPID)
    print("-------------------------------------------")
    print("商户号：" + CONST.BUSINESS_NO)
    print("-------------------------------------------")
    print("域名")
    print("域名：" + CONST.DOMAIN)
    print("商户号后台：" + CONST.BUSINESS_BACK)       #JSAPI支付授权目录
    print("CRM支付配置工具：" + CONST.CRM_PAY_CONFIG_TOOL)
    print("代理WS：" + CONST.PROXY_WS)
    print("-------------------------------------------")
    print("数据库")
    print("地址：" + CONST.DATABASE_ADDRESS)
    print("User：" + CONST.DATABASE_USER)
    print("Pwd：" + CONST.DATABASE_PWD)
    print("队列库：" + CONST.DATABASE_DTDSQUEUE)
    print("核心库1：" + CONST.DATABASE_HX1)
    print("核心库2：" + CONST.DATABASE_HX2)
    print("基础库：" + CONST.DATABASE_JICHU)
    print("配置库：" + CONST.DATABASE_PEIZHI)
    print("第三方支付库：" + CONST.DATABASE_THRPAY)
    print("-------------------------------------------")
    print("服务-SnoServer")
    print("服务路径：" + CONST.SNO_SERVER_PATH)
    print("服务名称：" + CONST.SNO_SERVER_NAME)
    print("端口：" + CONST.SNO_SERVER_PATH)
    print("服务地址：" + CONST.SNO_SERVER_ADDRESS)
    print("服务备注：" + CONST.SNO_SERVER_REMARK)
    print("-------------------------------------------")
    print("服务-CRMdz")
    print("服务路径：" + CONST.CRM_DZ_PATH)
    print("服务名称：" + CONST.CRM_DZ_NAME)
    print("端口：" + CONST.CRM_DZ_PATH)
    print("服务地址：" + CONST.CRM_DZ_ADDRESS)
    print("服务备注：" + CONST.CRM_DZ_REMARK)
    print("-------------------------------------------")
    print("服务-YwDetaildz")
    print("服务路径：" + CONST.YW_DETAIL_DZ_PATH)
    print("服务名称：" + CONST.YW_DETAIL_DZ_NAME)
    print("端口：" + CONST.YW_DETAIL_DZ_PATH)
    print("服务地址：" + CONST.YW_DETAIL_DZ_ADDRESS)
    print("服务备注：" + CONST.YW_DETAIL_DZ_REMARK)
    print("-------------------------------------------")
    print("服务-CRMWs")
    print("服务路径：" + CONST.CRM_WS_PATH)
    print("服务名称：" + CONST.CRM_WS_NAME)
    print("端口：" + CONST.CRM_WS_PATH)
    print("服务地址：" + CONST.CRM_WS_ADDRESS)
    print("服务备注：" + CONST.CRM_WS_REMARK)
    print("-------------------------------------------")
    print("服务-CRMWeb")
    print("服务路径：" + CONST.CRM_WEB_PATH)
    print("服务名称：" + CONST.CRM_WEB_NAME)
    print("端口：" + CONST.CRM_WEB_PATH)
    print("服务地址：" + CONST.CRM_WEB_ADDRESS)
    print("服务备注：" + CONST.CRM_WEB_REMARK)
    print("-------------------------------------------")
    print("服务-CRMManager")
    print("服务路径：" + CONST.CRM_MANAGER_PATH)
    print("服务名称：" + CONST.CRM_MANAGER_NAME)
    print("端口：" + CONST.CRM_MANAGER_PATH)
    print("服务地址：" + CONST.CRM_MANAGER_ADDRESS)
    print("服务备注：" + CONST.CRM_MANAGER_REMARK)
    print("-------------------------------------------")
    print("服务-CrmJichShuj")
    print("服务路径：" + CONST.CRM_JICHUSHUJU_PATH)
    print("服务名称：" + CONST.CRM_JICHUSHUJU_NAME)
    print("端口：" + CONST.CRM_JICHUSHUJU_PATH)
    print("服务地址：" + CONST.CRM_JICHUSHUJU_ADDRESS)
    print("服务备注：" + CONST.CRM_JICHUSHUJU_REMARK)
    print("-------------------------------------------")
    print("服务-CRMGuanD")
    print("服务路径：" + CONST.CRM_GUAND_PATH)
    print("服务名称：" + CONST.CRM_GUAND_NAME)
    print("端口：" + CONST.CRM_GUAND_PATH)
    print("服务地址：" + CONST.CRM_GUAND_ADDRESS)
    print("服务备注：" + CONST.CRM_GUAND_REMARK)
    print("-------------------------------------------")
    print("服务-CRMPeiZh")
    print("服务路径：" + CONST.CRM_PEIZH_PATH)
    print("服务名称：" + CONST.CRM_PEIZH_NAME)
    print("端口：" + CONST.CRM_PEIZH_PATH)
    print("服务地址：" + CONST.CRM_PEIZH_ADDRESS)
    print("服务备注：" + CONST.CRM_PEIZH_REMARK)
    print("-------------------------------------------")
    print("服务-CRMAccRecord")
    print("服务路径：" + CONST.CRM_ACC_RECORD_PATH)
    print("服务名称：" + CONST.CRM_ACC_RECORD_NAME)
    print("服务备注：" + CONST.CRM_ACC_RECORD_REMARK)
    print("-------------------------------------------")
    print("服务-CRMAccRecordAdd")
    print("服务路径：" + CONST.CRM_ACC_RECORD_ADD_PATH)
    print("服务名称：" + CONST.CRM_ACC_RECORD_ADD_NAME)
    print("服务备注：" + CONST.CRM_ACC_RECORD_ADD_REMARK)
    print("-------------------------------------------")
    print("服务-CRMAccRecordAdd")
    print("服务路径：" + CONST.CRM_MQ_CLIENT_PATH)
    print("服务名称：" + CONST.CRM_MQ_CLIENT_NAME)
    print("服务备注：" + CONST.CRM_MQ_CLIENT_REMARK)
    print("-------------------------------------------")
    print("服务-DataSync")
    print("服务路径：" + CONST.DATA_SYNC_PATH)
    print("服务名称：" + CONST.DATA_SYNC_NAME)
    print("服务备注：" + CONST.DATA_SYNC_REMARK)
    print("-------------------------------------------")
    print("服务-WeixinCallBack")
    print("服务路径：" + CONST.WX_CALLBACK_PATH)
    print("服务名称：" + CONST.WX_CALLBACK_NAME)
    print("服务备注：" + CONST.WX_CALLBACK_REMARK)
    print("-------------------------------------------")
    print("服务-CacheBuilder")
    print("服务路径：" + CONST.CACHE_BUILDER_PATH)
    print("服务名称：" + CONST.CACHE_BUILDER_NAME)
    print("服务备注：" + CONST.CACHE_BUILDER_REMARK)
    print("-------------------------------------------")
    print("服务-Heartbeat")
    print("服务路径：" + CONST.HEART_BEAT_PATH)
    print("服务名称：" + CONST.HEART_BEAT_NAME)
    print("服务备注：" + CONST.HEART_BEAT_REMARK)
    print("-------------------------------------------")
    print("支付加密")
    print("TenPayV3Model1：" + CONST.TENPAYV3_MODEL1)
    print("TenPayV3Model2：" + CONST.TENPAYV3_MODEL2)
    print("TenPayV3Model3：" + CONST.TENPAYV3_MODEL3)
    print("TenPayV3Model4：" + CONST.TENPAYV3_MODEL4)
    print("TenPayV3Model5：" + CONST.TENPAYV3_MODEL5)
    print("TenPayV3Model6：" + CONST.TENPAYV3_MODEL6)
    print("-------------------------------------------")
